# Generated by Django 2.1.dev20180216185855 on 2018-02-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threatapp', '0002_metafile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metafile',
            old_name='isImported',
            new_name='is_imported',
        ),
    ]
